### ISSUE TITLE
Disable cert caching

### ISSUE THREAD

**Issue by fnetX** [johansigfrids/expirator#1]
Hey, thank you for the add-on. It allowed me to warn webmasters of expiring certs three times and is also useful to learn about which cert providers websites use.

Is it possible to obtain the cert metadata from the connections (e. g. Firefox also knows about which certificate a websites uses)? This would allow the tool to not cache requests, which is a bit confusing if you replaced the cert, but don't get a notice from the tool.

Thank you.

**Comment by Mooninaut** [comment]
I'd also appreciate it if there was a button to manually clear the cache, when replacing the certificate on a website and checking my work.

**Comment by johansigfrids** [comment]
I added a Button to the extension pop-up window to clear the cache for the current tab. That way you get fresh data on a refresh, so you can see if the certificated has changed.
