### ISSUE TITLE
Expirator cache does not distinguish http from https

### ISSUE THREAD

**Issue by Mooninaut** [johansigfrids/expirator#2]
Steps to reproduce:

Ensure that "HTTPS-Only Mode" is disabled in Settings, Privacy and Security.

With an empty Expirator cache, visit http://example.com, then https://example.com
Observe that the https site has the same red open padlock badge as the http site.

With an empty Expirator cache, visit https://example.net, then http://example.net
Observe that the http site has the same green closed padlock badge as the https site.

This bug occurs for any site that permits both `http` and `https` connections, including sites that always redirect from http to https, and even sites with Strict-Transport-Security enabled if the http site is visited first.

One possible fix would be to only block on and cache connections using the https scheme, and automatically treat all other schemes as untrusted.

**Comment by johansigfrids** [comment]
I changed the cache key to be based on the URL origin, not hostname, so that it includes the scheme. This way the cache will not use the same cached data for both http and https.
